### ISSUE TITLE
update "Goal" button in Section 4

### ISSUE THREAD

**Issue by erinzstrenio** [CMSgov/cms-carts-seds#729]
This is more a "nice to have" but to be consistent with other references, the button text should be updated to match the template [doc](https://docs.google.com/document/d/1pyCyUQPJKVEIKZ3cBTM8ZThxNeLiUzIKPPr0xfImtv4/edit?ts=5f6cea35#heading=h.6dlnubezm3ff) and "goal" should be lowercase (not "Goal"):

- [ ] Change `Do you have another Goal in this list?` to be `Do you have another goal for this objective?`
- [ ] Change button below it from `Add another Goal` to `Add another goal`

**Comment by mgwalker** [comment]
Dev ref:
- The `Repeatables`/`Repeatable` component will likely need to be updated to accept separate parameters for the name of the repeatable type, the optional question text, and the button text, instead of naively deriving all of those from just the repeatable type name. We can fall back to the repeatable type name if the others aren't explicitly provided as a safety net
