### ISSUE TITLE
Update Computed/NaN to be more user-friendly

### ISSUE THREAD

**Issue by erinzstrenio** [CMSgov/cms-carts-seds#731]
As a user, I need to understand that certain values I enter are used to auto-calculate other values throughout the report. 

- [ ] Update `Computed` to `Automatically calculated` or something similar so it's clear for users
- [ ] Update `NaN` to `not valid` or something similar so it's clear for users
- [ ] Add text above each `Computed` component to clarify for users what's being computed (ie "Percent of children in the HSI program" and/or show the equation we're using to calculate the number,  "Number of children in HSI program/number of children in your CHIP program")

**Comment by mgwalker** [comment]
Dev reference:
- `Computed` is hard-coded text in the `SynthesizedValue` component, so we can change it there and it'll be reflected everywhere
- for `NaN`, we can either do a replacement in the `synthesize.js` utility, or we can update both `SynthesizedValue` and `SynthesizedTable` to check for `NaN`. (I prefer the former since it means just fixing it once.)
- the text for each computed value would be set in the JSON, as the `label` property for the `synthesized_value` fieldsets

**Comment by mgwalker** [comment]
Related to #699
