### ISSUE TITLE
Reassess file upload architecture and security controls

### ISSUE THREAD

**Issue by cjhskippy** [CMSgov/cms-carts-seds#778]
Before a user can do anything in CARTS, they are authenticated through OKTA.

In order to save a file, a secondary authentication takes place through AWS / Cognito.
(It is not clear if Cognito also uses Okta flows)

Cognito is not aware of permission levels controlled by the application.  It can’t tell the difference between administrators and state users, and it doesn’t know what state a user is associated with.  It just knows that you’re either authorized to save files or not authorized.

The frontend directly interacts with Cognito to upload a file.  This means:
- If you knew the name of the file you were looking for, any authorized user could look up files uploaded by any other state / user.  We didn’t explore whether this poses a risk of serious harm or is practically exploitable, but that should be considered further.
- We theorized that users may be able to upload a file to be associated with a different state than they are logged in with.  It’s not clear whether this is actually possible or any significant risk.

It also seems like we may need to review the intended user experience.  It doesn’t seem possible for a solution to work that does not extend the CARTS Django API.  The CARTS database needs to be aware of the file’s name, location, the US State it’s associated with for security controls, and the form + question that it’s related to.  Without somehow connecting uploaded files to the form, they will vanish as soon as a user reloads the page.

Scope that is not currently captured in the file upload story that needs better specification:
- Users need to be able to see files that have been previously uploaded into a form and download them.
- Security controls should be in place to ensure that files can only be accessed by users who have permission to see the report with which the uploaded file is associated.

**Comment by tadhg-ohiggins** [comment]
A major point is whether or not the Cognito setup works with Okta. If it does, we should be able to synthesize the relationship:

1. User uploads file, mediated by our frontend.
2. User gets confirmation of some sort, which includes the file ID.
3. Frontend sends the ID to Django, also including the context (i.e. what question it was uploaded in relation to).
4. Django verifies that the user has the correct permissions for the context.
    If that's not true, Django either deletes the file or, if that's not possible, doesn't include it in its own data, leaving it as a dangling reference.
5. If it is true, Django writes the context and the file identifier into the database with the appropriate associations for future access.

The uploaded files would presumably be accessible by everyone with the same job code as the uploading user. This is problematic, but if we're able to grant the uploading user group write-only access, we can likely use something along the lines of [presigned requests](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth) to handle downloads. This assumes that Django can get access to credentials that allow it to generate those presigned requests, which is certainly not a given, but from here doesn't seem like an insurmountable problem.

So if in step 4 the user uploaded a file that they could get the S3 identifier for (so that the frontend could pass that to Django) but didn't have permissions to read, the later steps would be:

6. Django makes a list of relevant files available, and to download them the user must request from Django a download URL; Django uses the app's knowledge of permissions to determine whether or not the user is entitled to that information.
7. If the user is, then Django and S3 created something like a presigned (temporary) URL and pass it to the user, who has some limited amount of time to use it.

Out of scope here are file management issues such as whether or not users can themselves delete previously uploaded files, whether or not they can overwrite previously-uploaded files, how many files can be associated with a given section, what will constitute the names of the files, how the files will be presented to the users, any kind of version control, etc.
