### ISSUE TITLE
AREMAC Endpoints

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [CMSgov/cms-carts-seds#787]
As a CARTS DSCP user I need to be able to do reporting within AREMAC so I can complete my responsibilities. 

AC:

- [ ] Create an API to allow for data access into CARTS from AREMAC

- [ ] Create an endpoint to allow how CARTS / AREMAC will access the API

Tech Note:

- [ ] Can we use existing endpoints for the states?

**Comment by andrewadcock** [comment]
AREMAC has requested access to pull directly from S3
They would also like parquet instead of JSON


From AREMAC
CARTS Data Ingestion - Requirements
CARTS team to AREMAC

**How will AREMAC connect?**
AREMAC team uses s3 access points. Event-based. SQS aka s3 put notification. 
**Does AREMAC have a preferred or required data format?**
Parquet is preferred
**How will CARTS authenticate requests from AREMAC?**
VPC pairing via access points
